### PR TITLE
Ported to MS3

### PR DESCRIPTION
**Pull request by jeetee**
As requested in https://musescore.org/en/node/6364#comment-1070515

### CODE REVIEW

**Comment by lasconic** [comment]
Hey, happy to transfer you the ownership of the project. I believe github will happily redirect. What do you think ?

**Comment by jeetee** [comment]
Fine by me.
Glad to see you still being alive ;-)

**Comment by lasconic** [comment]
Alive ? Always ;)

You'll need to delete your fork

**Comment by jeetee** [comment]
It is dead

**Comment by lasconic** [comment]
You have mail, or notification, or something.

**Comment by jeetee** [comment]
Seems to have worked out :)

**Pull request merged**
